### ISSUE TITLE
Develop Bash Script for Server Deployment

### ISSUE THREAD

**Issue by Kanchanop6509650229** [Kanchanop6509650229/CS360-qwerty#9]
**วัตถุประสงค์**:
- สร้าง bash script ที่ช่วยให้การ deploy และการตั้งค่าเซิร์ฟเวอร์เป็นไปอย่างอัตโนมัติ เพื่อลดความซับซ้อนและเพิ่มความสามารถในการทำซ้ำในการตั้งค่าเซิร์ฟเวอร์

**Task**:
- [ ] **กำหนดข้อกำหนดการ deploy**: ทบทวนความต้องการทางเทคนิคและข้อกำหนดการตั้งค่าสำหรับเซิร์ฟเวอร์ที่ต้องการ deploy รวมถึงการตั้งค่า server, dependencies ที่จำเป็น, และค่าการกำหนดคอนฟิก
- [ ] **เขียน script bash**: พัฒนา bash script ที่มีคำสั่งสำหรับการติดตั้งซอฟต์แวร์, การตั้งค่าและการกำหนดคอนฟิกเซิร์ฟเวอร์อัตโนมัติ
- [ ] **ทดสอบ script**: ทำการทดสอบ bash script ในสภาพแวดล้อมทดสอบเพื่อตรวจสอบความแม่นยำและความเสถียรของ script
- [ ] **เอกสารการใช้งาน**: จัดทำเอกสารที่อธิบายวิธีการใช้ bash script, ตัวเลือกการตั้งค่าต่างๆ และแนวทางในการแก้ไขปัญหาที่อาจเกิดขึ้น
